const keywords = {
  // keywords preferred in lower case but they are normalized in the pdf processing function
  keywordList: [
    "Yield",
    "Programmatic",
    "Data Science",
    "Data Analysis",
    "Staq",
    "Ad Operations",
    "Advertising Operations",
    "Datarama",
    "Ad Stack",
    "Ad Trafficking ",
    "Digital Media",
    "Ad Serving",
    "Campaign",
    "Optimization",
    "Advanced Advertising",
    "Linear TV",
    "Data Products",
    "Advertising Products",
    "Linear Audience",
    "Digital Advertising",
    "Open Exchange",
    "DFP",
    "SSP",
    "AdX",
    "DSP",
    "DMP",
    "SalesForce",
    'Full Stack',
    "Version Control",
    'e commerce'
  ],
  // All entries must be lower case
  keywordValue: {
    "yield": 5,
    "programmatic": 5,
    "data science": 5,
    "data anaylsis": 5,
    "staq": 5,
    "ad operations": 5,
    "advertising operations": 5,
    "datarama": 5,
    "ad stack": 5,
    "ad trafficking": 5,
    "digital media": 5,
    "ad serving": 5,
    "campaign": 5,
    "optimization": 5,
    "advanced advertising": 5,
    "linear audience": 5,
    "linear tv": 5,
    "data products": 5,
    "advertising products": 5,
    "digital advertising": 5,
    "open exchange": 5,
    "dfp": 5,
    "ssp": 5,
    "adx": 5,
    "dsp": 5,
    "dmp": 5,
    "salesforce": 5,
    "full stack": 5,
    "version control": 5,
    "e commerce": 5
  }
}

module.exports = keywords